titleHeaders: ["# "]
summaryHeaders: ["Описание", "Сводка"]
featuresHeaders: ["Черты", "Особенности"]
subclassesHeaders: ["Подклассы"]
columnMap: { level: "Уровень", proficiencyBonus: "Бонус мастерства", features: "Особенности" }
skillsHeaders: ["Навыки"]
toolsHeaders: ["Инструменты"]
languagesHeaders: ["Языки"]
equipmentHeaders: ["Снаряжение"]
talentHeaders: ["Таланты"]
sizeHeaders: ["Размер"]
speedHeaders: ["Скорость"]
traitsHeaders: ["Черты"]
heritagesHeaders: ["Наследия"]
synonyms: { }
regexes: { LevelCapture: "^Уровень\\s+(\\d+)" }
unitsSpeed: "ft"

