titleHeaders: ["# "]
summaryHeaders: ["Описание", "Сводка"]
featuresHeaders: ["Черты", "Особенности"]
subclassesHeaders: ["Наследия"]
columnMap: { }
skillsHeaders: ["Навыки"]
toolsHeaders: ["Инструменты"]
languagesHeaders: ["Языки"]
equipmentHeaders: ["Снаряжение"]
talentHeaders: ["Таланты"]
sizeHeaders: ["Размер"]
speedHeaders: ["Скорость"]
traitsHeaders: ["Черты"]
heritagesHeaders: ["Наследия"]
synonyms: { }
regexes: { LevelCapture: "^Уровень\\s+(\\д+)" }
unitsSpeed: "ft"

