mode: "collection"             # one file with many entries
entryHeaderLevel: 3            # ### <BACKGROUND NAME>
entrySectionHeaders: ["ПРЕДЫСТОРИИ"]  # Only parse entries under this H2 section
talentHeaders: ["ТАЛАНТ"]     # #### ТАЛАНТ under each entry
summaryHeaders: []             # not used by current extractor
skillsHeaders: ["Владение Навыками"]
equipmentHeaders: ["Снаряжение", "Начальное снаряжение"]
synonyms: { }
regexes: { }                   # backgrounds extractor does not use regexes
unitsSpeed: "ft"
